config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get 'about', to: 'pages#about', as: :about
  get 'gallery', to: 'pages#gallery', as: :gallery
  get 'contact', to: 'pages#contact', as: :contact
  get 'contacts', to: 'pages#contact'
  resources "contacts", only: [:new, :create]


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  attr_accessor :name, :email, :phonenumber, :message
  validates :email,
    :presence => :true
  validates :message, :presence => :true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protected

  def default_url_options
  { host: ENV["ritchiesgardens.herokuapp.com"] || "localhost:3000" }
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      ContactMailer.creation_confirmation(@contact).deliver_now
      flash.now[:notice] = "Your enquiry has been sent. We'll be in touch #{@contact.name}!"
      if URI(request.referer).path == "/contact"
        render "pages/contact"
      else
        render "pages/home"
      end
    else
      flash.now[:alert] = "#{@contact.errors.count} errors. Please re-enter enquiry below."
      if URI(request.referer).path == "/contact"
        render "pages/contact"
      else
        render "pages/home"
      end
    end
  end

  private

  def contact_params
    # *Strong params*: You need to *whitelist* what can be updated by the user
    # Never trust user data!
    params.require(:contact).permit(:name, :email, :phonenumber, :message)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @contact = Contact.new
  end

  def about
  end

  def gallery
  end

  def contact
    @contact = Contact.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # ajoutez la ligne ci-dessous pour que le helper fonctionne indifféremment
    # avec une image dans vos assets ou une url absolue
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f| %>
  <div class="form-error">
    <% if @contact.errors.any? %>
      <div id="error_explanation">
        <ul>
          <% @contact.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>
  <div class="form-group-total">
    <div class="form-group row">
      <%= f.label :name, class: "col-sm-2 col-form-label" %>
      <div class="col-sm-8">
         <%= f.text_field :name, class: 'form-control' %>
      </div>
      <div class="col-sm-2"></div>
    </div>
    <div class="form-group row">
      <%= f.label :email, class: "col-sm-2 col-form-label" %>
      <div class="col-sm-8">
        <%= f.text_field :email, class: 'form-control' %>
      </div>
       <div class="col-sm-2"></div>
    </div>
    <div class="form-group row">
      <%= f.label :phonenumber, "Phone Number", class: "col-sm-2 col-form-label" %>
      <div class="col-sm-8">
        <%= f.text_field :phonenumber, class: 'form-control' %>
      </div>
       <div class="col-sm-2"></div>
    </div>
    <div class="form-group row">
       <%= f.label :message, class: "col-sm-2 col-form-label" %>
      <div class="col-sm-8">
        <%= f.text_area :message, class: 'form-control' %>
      </div>
       <div class="col-sm-2"></div>
    </div>
    <div class="g-recaptcha" data-sitekey="6LcV6J4UAAAAAHPpa9hq4r_FCPGuWO0ekp9kSdC5"></div>
    <div class="contact-button-mob">
        <div class="col-sm-5 contact-button-mob"></div>
        <%= f.submit "Send Enquiry", class: 'btn btn-success col-sm-2 btn-contact-page' %>
        <div class="col-sm-5"></div>
    </div>
  </div>
<% end %>

app/views/contacts/new.html.erb
<div class="banner">
  <div class="container">
    <%= render 'form' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= favicon_link_tag %>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
    <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
  </body>
</html>

app/views/pages/about.html.erb
<% content_for :meta_title, "Garden Services - About | Ritchie's Gardens" %>

<div class="banner">
  <div class="container">
    <h1>ABOUT US</h1>
  </div>
</div>
<div class="content">
  <div class="container">
    <div class="about-content">
      <div class="row">
        <div class="col-sm-6">
          <div class="about-text">
            <h1>About Ritchie's Gardens</h1>
            <p>At Ritchie's Gardens we approach garden maintenance with best-practise horticultural techniques. A local business led by an enthusiastic and passionate professional who will treat your garden as his own. Founded in 2017 by Ben Ritchie, Ritchie's Gardens focuses on providing exceptional customer service along with efficient and professional horticulture services. Contact Ritchie's Gardens for all garden maintenance & soft landscaping enquires <%= link_to "here",contact_path, class: "about-text" %>.</p>
            <h3>Why pick Ritchie's Gardens for your next garden maintenance or landscaping job?</h3>
            <ul>
              <li>10+ years of experience</li>
              <li>Worked for premier garden businesses in Australia and overseas</li>
              <li>Qualified in Horticulture Cert 3</li>
              <li>Client relationships of 5+ years</li>
              <li>Timely and dependable service</li>
              <li>Friendly guys who just dig gardens!</li>
            </ul>
          </div>
        </div>
        <div class="col-sm-6">
          <div class="about-image">
            <%= image_tag "logo-white-stacked.png", height: 300, alt: "Ritchie's Gardens Logo White Stacked" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/contact.html.erb
<% content_for :meta_title, "Free Quote Today - Contact Us | Ritchie's Gardens" %>

<div class="banner">
  <div class="container">
    <div>
      <h1>CONTACT US</h1>
    </div>
  </div>
</div>
<div class="content">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-md-5">
        <div class="contact-details">
          <h1>Contact Ritchie's Gardens</h1>
          <h3>We'd love to hear from you!</h3>
          <p>Fill out the enquiry form or give us a call on <%= link_to "tel: +613 428 412 087", target: :_blank, class: "contact-phone-padding" do %>0428 412 087<% end %> and we'll get back to you as soon as we can.</p>
        </div>
      </div>
      <div class="col-xs-12 col-md-7">
        <div class="form-header">
          <h3>Enquire below for a free quote</h3>
        </div>
        <%= render 'contacts/form' %>
      </div>
    </div>
  </div>
</div>

app/views/pages/gallery.html.erb
<% content_for :meta_title, "Gallery - Garden Maintenace | Ritchie's Gardens" %>

<div class="banner">
  <div class="container">
    <div>
      <h1>GALLERY</h1>
    </div>
  </div>
</div>
<div class="content">
  <div class="container gallery-container">
    <div class="tz-gallery">
      <div class="row">
        <a class="lightbox" href="images/park.jpg">
          <% gallery = Cloudinary::Api.resources(:type => :upload, :prefix => "RG") %>
          <% gallery["resources"].each do |image| %>
            <%= link_to "#{image["secure_url"]}", class: "lightbox" do %>
              <div class="col-sm-6 col-md-4"><%= cl_image_tag("#{image["secure_url"]}", width: 300, height: 300, crop: :fill, :class =>'card', alt: "Ritchie's Gardens Gallery") %></div>
            <% end %>
          <% end %>
        </a>
      </div>
    </div>
  </div>
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.8.1/baguetteBox.min.js"></script>
<script>
  document.addEventListener('DOMContentLoaded', function() {
    baguetteBox.run('.tz-gallery');
  });
</script>

app/views/pages/home.html.erb
<% content_for :meta_title, "Garden Maintenance - Landscape Gardeners | Ritchie's Gardens" %>

<div id="home" class="banner" title="Ritchie's Gardnes banner">
  <div class="container">
    <div class="typed">
      <span id="banner-typed-text"></span>
    </div>
   <!--  <button type="button" class="btn btn-success">Danger</button> -->
  </div>
  <div id="section05" class="demo">
    <a href="#content"><span></span></a>
  </div>
</div>
<div id="content">
  <div class="container">
    <h1 class="heading-home">At Ritchie's Gardens, we really DIG gardens!</h1>
    <p class="location-home">Based in the Western Suburbs of Melbourne, Ritchie's Gardens service all inner Melbourne suburbs as well as Sunbury and Gisbourne.</p>
    <div class="pagebreak-plant">
      <i class="fab fa-pagelines"></i>
    </div>
    <div class="form-header">
      <h3>Enquire below for a FREE quote</h3>
      <p>We'll come to you to evaluate the work you need done and provide a quote within 2 business days.</p>
    </div>
    <%= render 'contacts/form' %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<div class="space"></div>
<% if notice %>
    <div class="alert alert-info alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><div aria-hidden="true">&times;</div></button>
      <%= notice %>
    </div>
  <% end %>
  <% if alert %>
    <div class="alert alert-warning alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><div aria-hidden="true">&times;</div></button>
      <%= alert %>
    </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="container">
  <div class="footer">
    <div class="footer-logo">
      <%=link_to root_path do %>
        <%= image_tag "logo-stacked.png", height: 80, class: "logo-footer" %>
      <% end %>
    </div>
    <div class="footer-phone">
      <i class="fas fa-phone-volume"></i>
      <%= link_to "tel: +613 428 412 087", target: :_blank do %>
        <span>0428 412 087</span>
      <% end %>
    </div>
    <div class="socials">
      <%= link_to "http://facebook.com/ritchiesgardens", target: :_blank do %>
        <i class="fab fa-facebook-square"></i>
      <% end %>
      <%= link_to "http://instagram.com/ritchiesgardens", target: :_blank do %>
        <i class="fab fa-instagram"></i>
      <% end %>
    </div>
  </div>
  <div class="footer-small-print">
    <div class="footer-abn">
      <span>ABN: 20 741 791 197</span>
    </div>
    <div class="footer-copyright">
      <i class="far fa-copyright"></i>
      <span>Copyright Caroline's Web</span>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar-fixed-top">
  <div class="navbar-wagon">
    <!-- Logo -->
    <%= link_to root_path, class: "navbar-wagon-brand" do %>
      <%= image_tag "logo.png", height: 70, alt: "Ritchie's Gardens Logo" %>
    <% end %>

    <!-- Right Navigation -->
    <div class="navbar-wagon-right hidden-xs hidden-sm">

      <!-- Links -->
      <%= link_to "Home", root_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "About", about_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Gallery", gallery_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Contact", contact_path, class: "navbar-wagon-item navbar-wagon-link" %>
    </div>

    <!-- Dropdown list appearing on mobile only -->
    <div class="navbar-wagon-item hidden-md hidden-lg">
      <div class="dropdown">
        <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><a href="/">Home</a></li>
          <li><a href="/about">About</a></li>
          <li><a href="/gallery">Gallery</a></li>
          <li><a href="/contact">Contact</a></li>
        </ul>
      </div>
    </div>
  </div>
</nav>